export const EVENTS = {
  OPEN: 'open',
  READY: 'ready',
  LOAD: 'load',
  REFLOW: 'reflow',
  RELOCATE: 'relocate',
  RESIZE: 'resize',
  RESIZED: 'resized',
  FORCERESIZE: 'forceresize',
  FORCERESIZED: 'forceresized',
  RENDER: 'render',
  RENDERED: 'rendered',
  KEYDOWN: 'keydown',
  SCROLL: 'scroll',
  SCROLLED: 'scrolled',
  LAYOUT: 'layout',
  UPDATEPAGESIZE: 'updatepagesize',
}